services:
  # 1. The Backend API
  - type: web
    name: face-attendance-backend
    env: image
    image: docker.io/sharna1/face-attendance-backend:latest
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0
    plan: free
    autoDeploy: true

  # 2. The Frontend (Optional: Vercel is better, but Render can do it too)
  # - type: web
  #   name: face-attendance-frontend
  #   env: node
  #   buildCommand: cd frontend && npm install && npm run build
  #   staticPublishPath: frontend/dist
