services:
  # 1. The Backend API
  - type: web
    name: face-attendance-backend
    env: image
    image: sharna1/face-attendance-backend:latest
    plan: free
    autoDeploy: true

  # 2. The Frontend (Optional: Vercel is better, but Render can do it too)
  # - type: web
  #   name: face-attendance-frontend
  #   env: node
  #   buildCommand: cd frontend && npm install && npm run build
  #   staticPublishPath: frontend/dist
